### ISSUE TITLE
creare una CDN

### ISSUE THREAD

**Issue by zenlor** [gtgames/machete#5]
Per pulire il codice e il repository si dovrebbe creare una CND per servire le librerie javascript e i widget

Si puo' utilizzare NGinx per montare una directory all'interno dei siti web o, semplicemente, utilizzare un dominio apposito

**Comment by Mikrobit** [comment]
Non stavamo usando frenzart.com per questo?

**Comment by zenlor** [comment]
se funziona WYMEditor siamo a cavallo :) altrimenti WYM va messo in un folder apposito da qualche parte

**Comment by zenlor** [comment]
il repository della CDN e' adesso https://github.com/gtgames/poorman_cdn

**Comment by zenlor** [comment]
la CDN adesso e' in alias sui sottodomini cdn.*
